language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview

script:
  - cargo test -- --test-threads=1
  - cargo clippy

matrix:
  allow_failures:
    # Clang on macOS
  include:
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8

env:
  global:
  - RUSTFLAGS="-D warnings"
