language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview

before_install:
  - echo "MATRIX_EVAL=${MATRIX_EVAL}"
  - echo "CC=$CC"
  - echo "CXX=$CXX"
  - eval "${MATRIX_EVAL}"

script:
  - cargo test -- --test-threads=1
  - cargo clippy

env:
  global:
  - RUSTFLAGS="-D warnings"

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  include:
    # GCC on Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
         - MATRIX_EVAL="CC=gcc-4.8 CXX=g++-4.8" # for conservative distributions
    # Clang on macOS
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8
    # GCC on macOS
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-9 && CXX=g++-9"
