language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview

script:
  - cargo test -- --test-threads=1
  - cargo clippy

matrix:
  allow_failures:
    # Clang on macOS
  include:
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-9 && CXX=g++-9"

env:
  global:
  - RUSTFLAGS="-D warnings"
